kyoushu_media:
    resource: "@KyoushuMediaBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_imagine:
    resource: .
    type:     imagine
